### ISSUE TITLE
remove graphic (or move) on smartphone version of site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/tsh-website#111]
**Is your feature request related to a problem? Please describe.**

Opening the site on a small screen makes you wonder what the content is about:

![image](https://user-images.githubusercontent.com/16557730/109813900-371e3b00-7c2e-11eb-93d7-47222a988301.png)

I'm always frustrated looking at the site on my phone, and not spotting what it is about. I just look at this giant image...

**Describe the solution you'd like**
I suggest we remove the picture from the mobile version, significantly decrease its size, have a "mobile version" of this graphic, or, instead, move it to another position.

**Additional context**

How do other sites do this? Look maybe at sites Jordan has developed?

**Comment by andreantonacci** [comment]
336dfbb
