### ISSUE TITLE
Development Call: tutorial Tilburg teaching template

### ISSUE THREAD

**Issue by kleintob** [tilburgsciencehub/tsh-website#112]
The tutorial should help someone who has only used Github before to use our educational template to build his own shiny website using our template.

I would put more weight on accessibility and maybe provide more detailed information somewhere further down. It would be great if someone who only knows Github could make his shiny website within 30 minutes or an hour. I'd like this style "it's easy, this is what you have to do". And then later some more advanced stuff.

The structure could be like this:
1. motivation: why it's a good idea to use this way of making a website: it's free, versioning, looks good, open source, ... (explain more, keep it short)
2. background information: a very brief explanation on how Hugo works, a brief explanation on what markdown is and how it works, and whatever else one needs to know
3. getting a simple website up and running, in steps (with example code that could be used so that people don't have to start from scratch

**Comment by andreantonacci** [comment]
d4d967b
