### ISSUE TITLE
fix the code boxes on article pages

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#15]

**Comment by andreantonacci** [comment]
The code boxes still do not have all the features we want.
Please, add:
- a quick "copy to clipboard" button
- a download button
- tabs for different programming languages and/or operating systems
- automatically show only 15 rows in long code boxes, and add a "Show more" at the bottom to expand it

![image](https://user-images.githubusercontent.com/50109671/104160555-9f505d80-53f1-11eb-812f-274dfb7e09f0.png)

**Comment by heyarviind** [comment]
What user can download by clicking on the download button ?

**Comment by heyarviind** [comment]
also, can the designer give the color scheme of the code? Because this color scheme is not enough to code a new scheme from scratch... Obviously, I can use the [Prism](https://prismjs.com/) for the scheme but I need all the colors for that...

**Comment by andreantonacci** [comment]
The user can download the code. This is meant for very long code. We either attach a file or it's automatically generated. For instance, if there's Pythond code in the code box, you can download a .py file.

All the colors used by the designer are available in the top-right corner on InVision.
![image](https://user-images.githubusercontent.com/50109671/104162536-15a28f00-53f5-11eb-8804-3f49a4ed0135.png)

**Comment by heyarviind** [comment]
okay, need to look into this...

**Comment by andreantonacci** [comment]
Please also add the copy button not only to full-size code boxes but also to single-line codes like these:
![image](https://user-images.githubusercontent.com/50109671/105385433-a4908200-5c13-11eb-9674-70d7810e1046.png)

**Comment by heyarviind** [comment]
if you want to add those feature to these boxes then you have to use codeblock shortcode to these code snippets too...

**Comment by heyarviind** [comment]
Also, can you specify download URL? Is download link really required?

**Comment by andreantonacci** [comment]
Of course we can manually specify the download link in the shortcode. If you mean that you need one to test with, just use any .txt or jpeg in the same folder as the article's.

**Comment by andreantonacci** [comment]
Great job!

**Comment by andreantonacci** [comment]
I spotted a more serious and important bug with the codeblock. When adding TWO different codeblocks on the same page, the second one won’t work. A second tab appears on the first codeblock but that’s not the desired behaviour. We want two different, separate codeblocks.

See here:  https://tsh-website.netlify.app/tutorials/project-setup/principles-of-project-setup-and-workflow-management/documenting-data/
