### ISSUE TITLE
add the breadcrumb trail

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#17]
Should be below the the menu bar and above the title and the article itself
![image](https://user-images.githubusercontent.com/50109671/103994549-6fa61900-5197-11eb-8cf3-21294bc695bc.png)

**Comment by heyarviind** [comment]
Hugo has some limitations, like for creating the breadcrumbs, Hugo gets the URL and breaks it and shows it in the breadcrumbs... but sometimes the title is not as same as post slug so it doesn't match.

![Screenshot 2021-01-08 at 4 07 24 PM](https://user-images.githubusercontent.com/21043614/104005830-b3b31100-51cb-11eb-9f7c-66b721cec03b.png)

like here, the title is different but the breadcrumb picks it from the URL so it is different.

**Comment by andreantonacci** [comment]
This is fine, no worries. So it will show the folder structure, not the actual article title, right?
@hannesdatta what do you think?

**Comment by heyarviind** [comment]
it will show the URL structure

**Comment by andreantonacci** [comment]
Because it shows the url structure instead of our title, it makes all our titles lowercase. Can you retain our capitalization or at least keep all the nouns capitalized? Thanks

**Comment by andreantonacci** [comment]
Perfect, thanks
