### ISSUE TITLE
add within article navigation

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#18]
Add the left menu for the navigation WITHIN the article
![image](https://user-images.githubusercontent.com/50109671/103994610-8482ac80-5197-11eb-82d3-0730c5a0b281.png)

**Comment by heyarviind** [comment]
is this navigation shows the menu of the current article (like heading and subheadings) or the links to the articles of the same section?

**Comment by andreantonacci** [comment]
This navigation shows the #headings and ##subheadings of the current article. It's just a menu for the article headers basically, similar to what's done elsewhere in other Hugo themes. Our old website had it too, a sort of "table of contents": 
![image](https://user-images.githubusercontent.com/50109671/104001002-53a67580-519f-11eb-9519-400fcc10eaab.png)

You can find an example here: http://tilburgsciencehub.com/examples/
Code available here: https://github.com/tilburgsciencehub/tilburg-science-hub

**Comment by heyarviind** [comment]
cool, will add this

**Comment by andreantonacci** [comment]
- Add more margin on the right. When the headings are too long, they come too close to the article
- Make the bold headings in the menu orange on hover too, similar to their child
- Add some margin below each "major" section (the ones in bold + their child elements), like here:

Yours (sections are very close to each other):
![Screenshot 2021-01-11 at 11 08 02](https://user-images.githubusercontent.com/50109671/104168022-a2e9e180-53fd-11eb-923f-90a957db3c62.png)


On InVision (more spread out):
![Screenshot 2021-01-11 at 11 08 38](https://user-images.githubusercontent.com/50109671/104168066-b301c100-53fd-11eb-80c2-8f151112a61c.png)

**Comment by andreantonacci** [comment]
I see that you implemented all the fixes except the the first one. When the title or the menu items are very long, they get too close to the article itself. Please, break the line earlier so that there's more margin between the left-menu and the article. 

![Screenshot 2021-01-12 at 10 18 55](https://user-images.githubusercontent.com/50109671/104294609-afcf0980-54bf-11eb-801a-79e18f6a1b93.png)

**Comment by andreantonacci** [comment]
This has been fixed on the specific page that I've shown above.
![Screenshot 2021-01-15 at 14 52 37](https://user-images.githubusercontent.com/50109671/104735042-64c42900-5741-11eb-9a98-86a70e39692f.png)

But this is not consistent everywhere. For instance, here:
![Screenshot 2021-01-15 at 14 51 56 1](https://user-images.githubusercontent.com/50109671/104735083-74437200-5741-11eb-8590-70ab036dc16f.png)
