### ISSUE TITLE
make article's title and left-menu fixed

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#19]
Make the title and the left-menu FIXED. They should always be there, they should not scroll down together with the article. Only the article scrolls down.

**Comment by heyarviind** [comment]
I have made it fixed, but due to the fixed navbar, it is overlapping...

![Screenshot 2021-01-08 at 10 40 18 PM](https://user-images.githubusercontent.com/21043614/104043889-7f0e7c00-5202-11eb-971b-1474a8b1b26b.png)

**Comment by andreantonacci** [comment]
Arvind, it appears to me that you made it sticky, not fixed. I don't really know myself which one works best for this occasion, but this how we want it to look:

https://user-images.githubusercontent.com/50109671/104167534-c4969900-53fc-11eb-8140-711153c07ffb.mov

I made it using position fixed and removing top: 0. HOWEVER, now it continues scrolling over the footer, which we don't want. It should stop before. Perhaps it's position sticky, but with a bottom value instead of top?

**Comment by andreantonacci** [comment]
And obviously we don't want the title to go over the article on the right...

**Comment by andreantonacci** [comment]
Now it's way better. It stops before the footer. However, when you scroll down it gets very close to the footer and it doesn't look good. Please add some margin to the left-menu.

I did it here adding it some margin-bottom to .col-lg-8, not sure if it's the proper way of doing it. But this is the idea.

https://user-images.githubusercontent.com/50109671/104293608-78ac2880-54be-11eb-87a8-ffc72b12160a.mov

**Comment by andreantonacci** [comment]
I see that this issue has been fixed but not everywhere. For instance, the menu still gets very close to the footer in the Educational Videos tutorial for some reason.

![image](https://user-images.githubusercontent.com/50109671/104734728-fa12ed80-5740-11eb-9e6b-b9f8fb368bf7.png)

**Comment by heyarviind** [comment]
I have added the space, but there is a bug like when you click on the link and it scrolls automatically, left menu overlaps the footer in some cases

**Comment by andreantonacci** [comment]
I think you're referring to the bug I mentioned on issue #25 - please fix it because it's very disturbing. Thanks!
