### ISSUE TITLE
fix white space below footer in Examples pages

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#20]
Currently, there's some white space below the footer in pages under "Examples". The footer should have no bottom margin.
![image](https://user-images.githubusercontent.com/50109671/103995947-733a9f80-5199-11eb-85a1-e7a33b5f6d51.png)

**Comment by heyarviind** [comment]
you mean by the white space right? and footer should always be fixed with the bottom of the screen.. no matter if there is content in the body or not.... am I right?

**Comment by andreantonacci** [comment]
Yes exactly, there should NOT be white space below it

**Comment by heyarviind** [comment]
okay got it.
