### ISSUE TITLE
fix menu structure

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#25]

**Comment by heyarviind** [comment]
can you add a little description here? I am not remembering which menu you are talking about.

**Comment by andreantonacci** [comment]
So, there are still some issues int he menu organization and I think this is the most important issue to fix first.

- First of all, why some tutorials are not accessible anymore? Clicking on "Principle of project setup and workflow management" links to the overview page. Same thing for "Educational videos".

![image](https://user-images.githubusercontent.com/50109671/104168910-0f191500-53ff-11eb-887a-13a123730749.png)

- "Contribute to Tilburg Science Hub" is still clickable, while it should not because it has child elements. Instead, "How to work with large files on github" is clickable, which IS correct because it has no child element.

![image](https://user-images.githubusercontent.com/50109671/104169081-4982b200-53ff-11eb-9df5-4126cbac1fc9.png)

So, in other words, if a bold header is an actual article, it should be clickable and link to that article. If it's just the title of a folder (hence it has child elements, the MD files inside the folder), it should NOT be clickable. 

One way I can think of approaching this issue is that if the title is from a _index.md file (for instance "Contribute to Tilburg Science Hub" from the _index.md inside the contribute-to-tilburg-science-hub folder), it should NOT be clickable. That's because _index.md files are inside folders, and if there's a folder then only the child MD files inside that folder should be clickable. If the title comes from a MD file named differently (like git-lfs.md in the case of "How to work with large files on github"), then it should be clickable on the menu.

If this is too complicated to set up automatically, we suggest to implement a new flag at the beginning of each article so that we can set it to true/false.

I hope it's clearer now.

**Comment by andreantonacci** [comment]
So, as we've just discussed, please update the following:

- In Tutorials, the big title on the left should be the Tutorial title, not the current MD file title.
- The current MD file title can be simply highlighted in orange in the left-menu navigation because it's the "selected" one
- Exclude from the footer all articles with indexexclude: true
- Reduce vertical margins between left-menu items (check on InVision for the precise height)
- Add a new second level of indentation for the left menu

Thanks!

**Comment by andreantonacci** [comment]
Awesome, thanks. Everything works as it should now, except this little bug: scrolling is fine, but if you click on anchor links on the left menu sometimes the page jumps to the bottom and the menu overlaps with the footer.
I suggest you fix this together with issue #19 

![image](https://user-images.githubusercontent.com/50109671/104442372-415c7b00-5595-11eb-8f48-7793c3b429dd.png)

**Comment by andreantonacci** [comment]
Hi Arvind, this issue is still present. When you click on anchor links to headers at the bottom of the page, these headers jump at the top and the menu on the left overlaps the footer.

![image](https://user-images.githubusercontent.com/50109671/104734264-46116280-5740-11eb-9c61-9c5ace3eb103.png)

**Comment by andreantonacci** [comment]
Arvind, I think the issue is still there: if I click on "Download Example Directory Structure" the menu still overlaps with the footer (on this page https://tsh-website.netlify.app/tutorials/project-setup/principles-of-project-setup-and-workflow-management/directories/#download-example-directory-structure)

![image](https://user-images.githubusercontent.com/50109671/105333430-0205de00-5bd6-11eb-825f-dfa1c7a480cd.png)

There's also another issue with the menu. I'm talking about issue #61. When the left menu is longer than the viewport, it's impossible to scroll and see its content before reaching the very end of the article (you can see this happening here: https://tsh-website.netlify.app/tutorials/project-setup/principles-of-project-setup-and-workflow-management/directories/).

I will talk to the designer about this issue but for the moment, just as a temporary solution, could you please let the menu scroll independently when it's so long? Basically having a second scroll bar, one for the menu, and the other one (already present) for the article.

**Comment by heyarviind** [comment]
this is happening because there are some empty links in the sidebar, need to look into this...

**Comment by andreantonacci** [comment]
Seems to work now but there's the other issue with long menus that I was talking about. I will close this issue and copy/paste what I wrote under issue #61.
