### ISSUE TITLE
add previous/next buttons at the bottom of article pages

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#26]

**Comment by andreantonacci** [comment]
Currently, the next page button navigates to the next tutorial, not within a tutorial, which is what we want.

**Comment by heyarviind** [comment]
Yes I get it, I am using Hugo default function to go to next page but I think we need a different algorithm for this

**Comment by andreantonacci** [comment]
Thanks for fixing the buttons too! However, in tutorials, they should navigate WITHIN the same tutorial (between the different .md files in the same folder), they should not show articles from somewhere else on the website.

![image](https://user-images.githubusercontent.com/50109671/105822414-5a652300-5fbc-11eb-8279-dae711c29597.png)

**Comment by andreantonacci** [comment]
Please hide titles inside the buttons on mobile, just show next / previous otherwise they get too big.
![image](https://user-images.githubusercontent.com/50109671/105823066-0149bf00-5fbd-11eb-8fb1-df01637ea636.png)

Instead of:

![image](https://user-images.githubusercontent.com/50109671/105822984-ebd49500-5fbc-11eb-9a5e-b64d62bdac85.png)

**Comment by heyarviind** [comment]
It is done

**Comment by andreantonacci** [comment]
Hi Arvind, the buttons look good now. However, they do not navigate to the correct pages! They should link to the previous or next .md file inside a tutorial folder (use the weight specified inside the articles).

> Thanks for fixing the buttons too! However, in tutorials, they should navigate WITHIN the same tutorial (between the different .md files in the same folder), they should not show articles from somewhere else on the website.
> 
> ![image](https://user-images.githubusercontent.com/50109671/105822414-5a652300-5fbc-11eb-8279-dae711c29597.png)

**Comment by andreantonacci** [comment]
Hi Arvind, the buttons still don't work.

- **Inside tutorials**:
The next button on this page (https://tsh-website.netlify.app/tutorials/project-setup/principles-of-project-setup-and-workflow-management/overview/) should lead to the next .md file inside that folder, which is "Pipelines and Project Components"(/pipeline/). Instead, it links to the next tutorial (Data sharing).
![image](https://user-images.githubusercontent.com/50109671/105998032-88c22b80-60ac-11eb-9847-e49146e5d402.png)

- **Inside Building Blocks**:
The buttons work properly but they skip every other article (in an alternate way). For instance, if you're on the page with weight 3, the next button will link you to the page with weight 5, and the previous button to the page with weight 1. Instead they should link to the pages with weight 4 and 2, respectively.

For instance, the next button on the Python page links to R and RStudio, not Python packages as it should.
![image](https://user-images.githubusercontent.com/50109671/105998646-2cabd700-60ad-11eb-9bcf-e0801908498f.png)

Another example: the next button on the Snakemake page links to Teamviewer (not to Making Path Settings Permanent as it should) and the previous button to Command Line Tools instead of the correct Automation with GNU Make.
![image](https://user-images.githubusercontent.com/50109671/105998994-772d5380-60ad-11eb-9db2-46f72a25b7a9.png)

You can see the correct order they should follow: simply the descending order shown on the menu.
![image](https://user-images.githubusercontent.com/50109671/105999070-9330f500-60ad-11eb-8349-f5ae4b5bc5a5.png)

**Comment by andreantonacci** [comment]
Awesome thanks!
