### ISSUE TITLE
implement keywords

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#29]
We sometimes included some keywords at the end of an article to make it discoverable through search and for SEO purposes.
Are those needed? Can we implement them as a tag at the beginning of the article (next to title, date, draft, etc.)?
![image](https://user-images.githubusercontent.com/50109671/104011174-fcf46800-51ad-11eb-9560-767528f03ca8.png)

**Comment by heyarviind** [comment]
ummm can we hide them on the page, Google will still find it for the SEO purpose

**Comment by andreantonacci** [comment]
We want them as a hidden field at the beginning of the page, similar to the description at #30

**Comment by heyarviind** [comment]
Added at the top of the page, just add description and keywords in the params

`keywords: "some, random,keywords"
description: some description`
