### ISSUE TITLE
make the article description and keywords work in the search

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#30]
Add a description field at the beginning of an article, like this:
![image](https://user-images.githubusercontent.com/50109671/104035122-0db6d500-51d2-11eb-8b7e-2ea328b3cc1f.png)

This can be used for SEO purposes and to fetch a description somewhere else on the website, like here:
![Screenshot 2021-01-08 at 16 54 30](https://user-images.githubusercontent.com/50109671/104035268-3939bf80-51d2-11eb-83ba-b86d03542027.png)

**Comment by andreantonacci** [comment]
This is similar to what we want for keywords/tags at #29

**Comment by heyarviind** [comment]
okay

**Comment by heyarviind** [comment]
Added at the top of the page, just add description and keywords in the params

`keywords: "some, random,keywords"
description: some description`

**Comment by andreantonacci** [comment]
Both the description and keywords needs to be in quotes? Each keyword is between quotes? Is the space character or the comma used as a separator for the keywords?

**Comment by heyarviind** [comment]
you can type in any way in quotes or without... also you can space but the comma is a must in keywords.

**Comment by andreantonacci** [comment]
Are the description and keywords searchable (through the search bar)? Do they really work to improve the search function?

**Comment by heyarviind** [comment]
for now, they don't. The search functionality works with just the title for now.

**Comment by andreantonacci** [comment]
Fine for now, but we actually want them to work

**Comment by andreantonacci** [comment]
I'll rename the issue accordingly

**Comment by heyarviind** [comment]
Sure
