### ISSUE TITLE
styling of `example` shortcode

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/tsh-website#33]
I have added an example shortcode.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/16557730/104157518-8fce1600-53eb-11eb-9fa2-a9e61723ad36.png">

- Please find a good icon (note: example is something that puts theory into practice; a few descriptives: put into action, example from practice, business practice, illustration)
- Please choose some proper background color and add to CSS.

**Comment by heyarviind** [comment]
I guess I have already implemented this

**Comment by hannesdatta** [comment]
Hey Arvind,
no need to address this right away. Andrea will be discussing the priorities with you (I have just briefed him, so he'll be in touch shortly).

**Comment by hannesdatta** [comment]
I have added the snippet for example, but the icon isn't good yet, and neither is the color ;)

**Comment by heyarviind** [comment]
Alright

**Comment by heyarviind** [comment]
icon and color for the example shortcode?

**Comment by andreantonacci** [comment]
As regards the icon, please use the summary one (the pencil). For the summaries, use instead this one: https://thenounproject.com/search/?q=summary&i=3082142 (or anything similar in case you're forced to use a different source).

As regards the colors for examples, use #F0F7FF for the background, and a more saturated version of that hue for the icon color.

**Comment by andreantonacci** [comment]
Perfect, thanks
