### ISSUE TITLE
formatting issue with numbered lists

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/tsh-website#34]
@andreantonacci, is this a styling issue?

<img width="754" alt="image" src="https://user-images.githubusercontent.com/16557730/104159345-6ca56580-53ef-11eb-9baa-2c564499730e.png">

```
## Keep in mind our key goals

Our platform focuses on __usability__ (i.e., ability to quickly copy-paste code or download templates), __speed__ (i.e., loading time), and __attractiveness__ (i.e., visual appeal, “state-of-the-art” look, good writing).

Our platform is a (classical) two-sided market.

1. We attract __novice and expert users__ that *use* our content in their work, and
2. We build a __community of content creators__ that have an outspoken vision on how to conduct science efficiently.
```

Seems the list has a smaller font size than the body...

**Comment by andreantonacci** [comment]
For some reason, adding an empty line between each numbered point fixes the issue. 

This works:
```
1. something

2. something more
```

This renders in a smaller font:
```
1. something
2. something more
```

@heyarviind could you look into this later on? It's very low-priority

**Comment by heyarviind** [comment]
Sure
