### ISSUE TITLE
add a "related article" section at the bottom of article pages

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#38]
- It can fetch similar articles automatically using the search functionality (same keywords or similar titles)

**OR**

- It can be an optional feature that we turn on/off manually on each article in case we have to manually specify what are the related articles

![image](https://user-images.githubusercontent.com/50109671/104171658-44276680-5403-11eb-9f04-4f248e45e7ce.png)

**Comment by heyarviind** [comment]
what query should I search when I am in the article? Obviously, I can search the title and but it would return only a single result which is the title itself.

maybe I can find articles from the same section?

**Comment by andreantonacci** [comment]
Yes, or use articles with the same tags! The ones we specify at the beginning on articles

**Comment by heyarviind** [comment]
I've added the related posts, but it picks posts randomly from the current section which is not very good... can you add some related posts manually in the article?

**Comment by andreantonacci** [comment]
We can manually specify them in the article for the moment and hopefully you'll manage to automatically add related posts using the keywords specified in the articles

**Comment by heyarviind** [comment]
I have added the related keywords searching, you can add some and we can test on some articles

**Comment by andreantonacci** [comment]
It works great on this page https://tsh-website.netlify.app/tutorials/educational-support/educational-videos/equipment-edu-videos/

But for some reason it doesn't work on this one https://tsh-website.netlify.app/tutorials/educational-support/educational-videos/educational-videos-overview/

I specified the exact same keywords for all three articles of the Educational Video tutorial.

Anyway, can you please hide this related posts section entirely when there are no matching keywords? If it's empty it should not be visible:
![image](https://user-images.githubusercontent.com/50109671/105018787-b3293e80-5a45-11eb-983e-cec77a743c94.png)
