### ISSUE TITLE
anchor links jump behind the navbar

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#45]
Once you click on an anchor link, the page jumps to the anchor shown at the very top of the viewport obviously. The problem is that we have a fixed navbar that covers everything behind itself. Can you make it jump below the navbar so that it's more clear and useful? 
Thanks
![Screenshot 2021-01-12 at 10 31 41](https://user-images.githubusercontent.com/50109671/104296097-8a42ff80-54c1-11eb-835b-380842dbd681.png)

**Comment by heyarviind** [comment]
Yes, I know about this issue and it would be hard to debug this as we are overlaying the navbar...

**Comment by andreantonacci** [comment]
https://css-tricks.com/hash-tag-links-padding/
https://pixelflips.com/blog/anchor-links-with-a-fixed-header

**Comment by andreantonacci** [comment]
Great job here. This works well with inner levels in the navigation (links that are not bold on the menu), like this subheading:
![image](https://user-images.githubusercontent.com/50109671/105332946-74c28980-5bd5-11eb-8481-cc28b5ddcd60.png)

But not so much with upper level ##headings (bold links on the menu) like this one (it's still behind the navbar as you can see):
![image](https://user-images.githubusercontent.com/50109671/105333050-902d9480-5bd5-11eb-9eb2-bac87f0ed532.png)

**Comment by andreantonacci** [comment]
Cool, thanks
