### ISSUE TITLE
check why citations don't work inside admonitions

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#50]
Citations in the body work fine. However, if they're in an admonition (like in a summary in this example), they don't. See here: https://tsh-website.netlify.app/tutorials/other-category/implement-an-efficient-and-reproducible-workflow/finish/
![Screenshot 2021-01-12 at 16 57 51](https://user-images.githubusercontent.com/50109671/104339239-aa8db100-54f7-11eb-88d6-8883e7386fc7.png)

**Comment by heyarviind** [comment]
Hugo is not able to pick citations from shortcodes, need to raise an issue in hugo repo

**Comment by andreantonacci** [comment]
Alright, please keep us informed, thanks
