### ISSUE TITLE
fix the search functionality

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#54]
On issue #30 you said that the search currently works with the titles only. However, that's not always the case.

I think the search function is not working properly.

For instance, we have some articles with "videos" in their titles but they don't show up in the search (no suggested articles found as shown below):
![image](https://user-images.githubusercontent.com/50109671/104716431-3a19a680-5728-11eb-87bc-e4f130ab4ac9.png)

I'd say work on this issue together with #30.

**Comment by heyarviind** [comment]
Need to think about this, the search in the header should return all the results but the search in tutorials and building blocks should return their respective results...

I am writing this module from scratch.

**Comment by andreantonacci** [comment]
For your reference, an article with "videos" in its title that I mentioned before is: https://tsh-website.netlify.app/tutorials/educational-support/educational-videos/equipment-edu-videos/
