### ISSUE TITLE
decide how to handle unscrollable menus

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#61]
When the within article navigation is longer than the viewport, it's impossible to scroll and see its content before reaching the very end of the article.
See here: https://tsh-website.netlify.app/tutorials/project-setup/principles-of-project-setup-and-workflow-management/directories/

**Comment by andreantonacci** [comment]
I will talk to the designer about this issue but for the moment, just as a temporary solution, could you please let the menu scroll independently when it's so long? Basically having a second scroll bar, one for the menu, and the other one (already present) for the article.

**Comment by andreantonacci** [comment]
Hey Arvind, thanks for implementing this but it looks worse than I expected. Especially on shorter menu, the scroll bar is still there and annoying.
![image](https://user-images.githubusercontent.com/50109671/105826926-9bac0180-5fc1-11eb-941a-1164e1f0fb16.png)

Have you got any ideas on how to solve this issue without making it look that bad?

Perhaps, instead of making the menu scrollable, we could momentarily remove the scroll bar and hide all the anchor links in these long menus. This should make the menus shorter because they would only show the links to the different .md files in a folder, and not the # links within an article. What do you think?

**Comment by andreantonacci** [comment]
I'm closing this issue because we keep it the scroll bar as it is for the moment.

**Comment by andreantonacci** [comment]
Arvind, please bring back the scroll bar. It's now disappeared. What I meant with my previous comment is that we want to keep it!
Thanks

**Comment by heyarviind** [comment]
Oh Okay 😅
