### ISSUE TITLE
show html pages

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#63]
Hi Arvind, we have some html pages (for instance at /tutorials/project-setup/principles-of-project-setup-and-workflow-management/structure_spotify_2018.html) that we would like to link from the articles. Howevere, the links don't work. I guess that's because Hugo is not treating them just as "assets" (for instance we have some .png files inside these folders too, and they work). How could we solve this?

**Comment by heyarviind** [comment]
just add the `../ ` in front of the link and it will work

![Screenshot 2021-01-26 at 12 27 37 PM](https://user-images.githubusercontent.com/21043614/105810982-e7ff3d80-5fd1-11eb-9832-b6a1a629adaf.png)
