### ISSUE TITLE
add main homepage graphics

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#65]
Hi Arvind, there's an illustration now on InVision for the homepage. Can you please implement it?
Thanks

![image](https://user-images.githubusercontent.com/50109671/105334419-24e4c200-5bd7-11eb-806a-12966888e34c.png)

**Comment by heyarviind** [comment]
I cant group the illustration, can you ask the designer to group it so that I can export it

**Comment by andreantonacci** [comment]
Hi Arvind, the designer should have grouped the illustration now in a .svg
