### ISSUE TITLE
navigation for content

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/tsh-website#7]
I have started having a menu hierarchy for tutorials.

```
- Project setup
   o Tutorial 1: Workflow principles
- Next project category
   o Some other tutorial
```

![image](https://user-images.githubusercontent.com/16557730/103990785-0c65b800-5192-11eb-9988-4a22610d3f88.png)

Yet, the menu renders this item twice. Once as a child to "project setup" (which is what we want), and once as its own menu item.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/16557730/103990851-230c0f00-5192-11eb-9e8b-7136aef53418.png">

Last, when clicking on project setup --> principles, I get an empty page.

**Comment by andreantonacci** [comment]
I guess the issue here is that sometimes we want the bolder titles to be clickable (when no child) and sometimes we don't, treating it just as a column header and not actual content. @heyarviind

**Comment by heyarviind** [comment]
@andreantonacci got it. let me see how can I fix this

**Comment by heyarviind** [comment]
is this one fixed? @andreantonacci
