### ISSUE TITLE
make "tutorialtitle" to appear on the menu, not "title"

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#70]

**Comment by andreantonacci** [comment]
Can you please do the same for the tutorials overview page and in the footer? They should display tutorialtitle, not just the first .md file's title, thanks
![image](https://user-images.githubusercontent.com/50109671/105732111-660b0800-5f30-11eb-9cf5-cdeaec8c34ab.png)

![image](https://user-images.githubusercontent.com/50109671/105732129-6b685280-5f30-11eb-8e4f-f5fd147987e7.png)

**Comment by heyarviind** [comment]
tutorialtitle is the same throughout the pages so it will appear the same for now in the footer and tutorials overview page

**Comment by andreantonacci** [comment]
Hi Arvind,

Only the bold header should get the tutorialtitle. All the other links below should get single .md pages titles, otherwise we get something like this:
![image](https://user-images.githubusercontent.com/50109671/105821570-4cfb6900-5fbb-11eb-9b6c-9ddc4020b4a9.png)

**Comment by andreantonacci** [comment]
Hi Arvind, this is now fixed on the overview page, but not in the footer!
![image](https://user-images.githubusercontent.com/50109671/105844960-52b47700-5fda-11eb-91ce-8ed22154aded.png)
